#! /bin/sh

sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a obs desktop='^5' focus=on

# Helps screen to say alive despite inactivity or say watching videos
xset -dpms
xset s off

# Setting the pointer to left pointer
xsetroot -cursor_name left_ptr

# Restoring the Background Images
nitrogen --restore &

# Adjusting the Monitors Layout and Configuration
~/.dotfiles/screenlayout.sh

# A light weight compositor for Ubuntu. Used for Shadows & Transparency
xcompmgr &
